# Generated by Django 5.0.1 on 2024-01-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productvariant_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-total_stock', '-created_at']},
        ),
        migrations.AlterField(
            model_name='product',
            name='total_stock',
            field=models.PositiveIntegerField(default=0, help_text='Total stock of product including all variants, must be greater than 0 '),
        ),
    ]
