# Generated by Django 5.0.1 on 2024-01-17 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_options_alter_product_total_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['total_stock', '-created_at']},
        ),
    ]
