# Generated by Django 5.0.1 on 2024-02-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='share_link',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='share_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
