# Generated by Django 5.0.1 on 2024-01-22 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_unique_together'),
        ('product', '0003_review_rating_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'variant_product')},
        ),
    ]
