# Generated by Django 5.0.1 on 2024-01-17 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_orderitem_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discount',
            field=models.FloatField(default=0.0, help_text='Discount in percentage, should be between 0.0 and 100.0 ', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(default=0.0, help_text='Total price of order, should be more than 1.0 ', validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
    ]
