# Generated by Django 5.0.1 on 2024-01-17 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_order_is_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_ordered',
        ),
    ]
